server.port=8080

# Cuenca - Puerto 5432
banco.cuenca.jdbc-url=jdbc:postgresql://localhost:5432/banco_austro
banco.cuenca.username=admin
banco.cuenca.password=admin123

# Quito - Puerto 5433
banco.quito.jdbc-url=jdbc:postgresql://localhost:5433/banco_austro
banco.quito.username=admin
banco.quito.password=admin123

# Guayaquil - Puerto 5434
banco.guayaquil.jdbc-url=jdbc:postgresql://localhost:5434/banco_austro
banco.guayaquil.username=admin
banco.guayaquil.password=admin123
